# Generated by Django 3.2.13 on 2025-03-05 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_remove_contractmodel_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='end_user',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='end_users',
            field=models.ManyToManyField(blank=True, related_name='endusers', to=settings.AUTH_USER_MODEL, verbose_name='Конечные пользователи'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
