# Generated by Django 3.2.13 on 2026-03-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_usertokenmodel_uid'),
        ('contracts', '0005_auto_20250305_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='accounts.organizationmodel', verbose_name='Организация'),
        ),
    ]
