# Generated by Django 3.2.13 on 2026-04-06 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0006_contractmodel_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractEndUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contractmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_contractmodel_end_users',
                'unique_together': {('contractmodel', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_users',
            field=models.ManyToManyField(blank=True, related_name='endusers', through='contracts.ContractEndUser', to=settings.AUTH_USER_MODEL, verbose_name='Конечные пользователи'),
        ),
    ]
