# Generated by Django 3.2.13 on 2026-04-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_usertokenmodel_uid'),
        ('contracts', '0007_auto_20260406_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractenduser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organizationmodel', verbose_name='Организация конечного пользователя'),
        ),
    ]
