# Generated by Django 3.2.13 on 2026-06-28 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractenduser_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractmodel',
            options={'ordering': ['number', 'organization__name'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
    ]
