# Generated by Django 3.2.13 on 2025-03-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0079_appcommentmodel_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmodel',
            options={'ordering': ['status__priority', '-id'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
