# Generated by Django 3.2.13 on 2025-05-04 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0080_alter_applicationmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='engineers',
            field=models.ManyToManyField(blank=True, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Инженеры'),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='old_engineer',
            field=models.ForeignKey(blank=True, db_column='temp_engineer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Инженер (старое)'),
        ),
    ]
