# Generated by Django 3.2.13 on 2025-05-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0081_auto_20250504_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='old_engineer',
        ),
    ]
