# Generated by Django 3.2.13 on 2026-03-12 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0005_auto_20250305_1645'),
        ('applications', '0082_auto_20250504_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='contact_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_applications', to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь'),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='contracts.contractmodel', verbose_name='Контракт'),
        ),
    ]
