# Generated by Django 3.2.13 on 2026-05-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0083_auto_20260312_1131'),
        ('applications', '0084_auto_20260521_2131'),
    ]

    operations = [
    ]
