# Generated by Django 3.2.13 on 2026-06-28 06:58

import applications.models
from django.db import migrations, models
import django.db.models.deletion
import integrator.apps.validators


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0085_merge_0083_auto_20260312_1131_0084_auto_20260521_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='contact',
        ),
        migrations.CreateModel(
            name='AppCommentDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, verbose_name='Наименование файла')),
                ('document', models.FileField(upload_to=applications.models.comment_file_name, validators=[integrator.apps.validators.validate_format, integrator.apps.validators.validate_size], verbose_name='Файл')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.appcommentmodel', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Файл комментария',
                'verbose_name_plural': 'Файлы комментариев',
            },
        ),
    ]
